### ISSUE TITLE
Welcome message isn't quoted

### ISSUE THREAD

**Issue by declension** [guidowojke/ansible-role-jamulus#1]
First - thanks for an excellent Ansible role! Really useful and much better than I was about to try...

## Steps
 * Set welcome message to something with a single quote, e.g. `This won't work!`
 * Run the role

## Expected: 
* Starts OK

## Actual
```
fatal: [****.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "Error loading unit file 'jamulus-server': org.freedesktop.systemd1.BadUnitSetting \"Unit
jamulus-server.service has a bad unit file setting.\""}
```

**Comment by guidowojke** [comment]
Problem is solved with latest release 1.0.2
